version: '3.8'
services:

  postgresql:
    image: postgis/postgis:15-3.3
    container_name: citymonitor-postgresql
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_ROOT_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=CityMonitorDB'
    volumes:
      - ./resources/db_create.sql:/docker-entrypoint-initdb.d/db_create.sql

  admin-panel:
    image: city-monitor-web
    container_name: city-monitor-web
    restart: always
    ports:
      - '8088:8085'
    environment:
      - 'DATABASE_URL=jdbc:postgresql://postgresql:5432/CityMonitorDB'
      - 'DATABASE_USERNAME=postgres'
      - 'DATABASE_PASSWORD=postgres'
      - 'TZ=Europe/Kiev'
    depends_on:
      - postgresql

  telegram-bot:
    image: city-monitor-bot
    container_name: city-monitor-bot
    environment:
      - 'DATABASE_URL=jdbc:postgresql://postgresql:5432/CityMonitorDB'
      - 'DATABASE_USERNAME=postgres'
      - 'DATABASE_PASSWORD=postgres'
      - 'TZ=Europe/Kiev'
    depends_on:
      - postgresql
