version: '3.8'
services:

  postgresql:
    image: postgis/postgis:15-3.3
    container_name: citymonitor-postgresql
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}'
      - 'POSTGRES_USER=${DATABASE_USER}'
      - 'POSTGRES_PASSWORD=${DATABASE_PASSWORD}'
      - 'POSTGRES_DB=CityMonitorDB'
    volumes:
      - ./resources/db_create.sql:/docker-entrypoint-initdb.d/db_create.sql

  admin-panel:
    build:
      context: city-monitor-web
      dockerfile: Dockerfile
    container_name: city-monitor-web
    restart: always
    ports:
      - '8088:8085'
    environment:
      - 'DATABASE_URL=${DATABASE_URL}'
      - 'DATABASE_USER=${DATABASE_USER}'
      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
      - 'TZ=${TIME_ZONE}'
      - 'MAP_START_POSITION_LATITUDE=${MAP_START_POSITION_LATITUDE}'
      - 'MAP_START_POSITION_LONGITUDE=${MAP_START_POSITION_LONGITUDE}'
      - 'GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}'
      - 'TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}'
    depends_on:
      - postgresql

  telegram-bot:
    build:
      context: city-monitor-bot
      dockerfile: Dockerfile
    container_name: city-monitor-bot
    environment:
      - 'DATABASE_URL=${DATABASE_URL}'
      - 'DATABASE_USER=${DATABASE_USER}'
      - 'DATABASE_PASSWORD=${DATABASE_PASSWORD}'
      - 'TZ=${TIME_ZONE}'
      - 'TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}'
      - 'TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}'
    depends_on:
      - postgresql
