name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cd into repo
        uses: actions/checkout@v3

      - name: set up Java and Maven
        uses: actions/setup-java@v3 
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: run tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report city-monitor-bot
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: ./city-monitor-bot/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          fail-on-empty: false
          
      - name: Report city-monitor-web
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Report
          path: ./city-monitor-web/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          fail-on-empty: false

  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dbelyaev/action-checkstyle@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          checkstyle_config: sun_checks.xml

  docker-build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Dashboard to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push city-monitor-web
        uses: docker/build-push-action@v4
        with:
          context: ./city-monitor-web
          push: true
          tags: denisenk00/city-monitor-web:latest

      - name: Build and push city-monitor-bot
        uses: docker/build-push-action@v4
        with:
          context: ./city-monitor-bot
          push: true
          tags: denisenk00/city-monitor-bot:latest
