name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cd into repo
        uses: actions/checkout@v3

      - name: set up Java and Maven
        uses: actions/setup-java@v3 
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      - name: run tests
        run: mvn test

  docker-build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Dashboard to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push city-monitor-web
        uses: docker/build-push-action@v4
        with:
          context: city-monitor-web
          file: Dockerfile
          push: true
          tags: denisenk00/city-monitor-web:latest

      - name: Build and push city-monitor-bot
        uses: docker/build-push-action@v4
        with:
          context: city-monitor-bot
          file: Dockerfile
          push: true
          tags: denisenk00/city-monitor-bot:latest
