name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Upload repository
        uses: actions/checkout@v3

      - name: set up Java and Maven
        uses: actions/setup-java@v3 
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven

      - name: Build with checkstyle and spotbugs
        run: mvn --batch-mode -DskipTests verify checkstyle:checkstyle spotbugs:spotbugs

      - name: Checkstyle report parsing
        uses: jwgmeligmeyling/checkstyle-github-action@master
        with:
          path: '**/checkstyle-result.xml'

      - name: Spotbug report parsing
        uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugsXml.xml'

      - name: run tests
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test

      - name: Report city-monitor-bot
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test report for city-monitor-bot
          path: ./city-monitor-bot/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          fail-on-empty: false
          
      - name: Report city-monitor-web
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test Report for city-monitor-web
          path: ./city-monitor-web/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
          fail-on-empty: false

  docker-build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Upload repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Dashboard to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push city-monitor-web
        uses: docker/build-push-action@v4
        with:
          context: ./city-monitor-web
          push: true
          tags: denisenk00/city-monitor-web:latest

      - name: Build and push city-monitor-bot
        uses: docker/build-push-action@v4
        with:
          context: ./city-monitor-bot
          push: true
          tags: denisenk00/city-monitor-bot:latest
